name 'devon-opsview'
author 'Devon Peters <devon.peters@gmail.com>'
description 'Puppet types and providers to manage Opsview objects, such as hosts, servicechecks, servicegroups, etc.'
source 'https://github.com/dpeters/puppet-opsview'
project_page 'https://github.com/dpeters/puppet-opsview'
version '0.4.0'
